version: "3.9"

services:
  aiostreams:
    image: ghcr.io/viren070/aiostreams:latest
    container_name: aiostreams
    restart: unless-stopped
    ports:
      - "8085:3000"
    environment:
      # ===== ESSENTIAL ADDON SETUP =====
      - ADDON_NAME=AIOStreams
      - ADDON_ID=aiostreams.spatialdev.com.au
      - PORT=3000
      - BASE_URL=https://aiostreams.spatialdev.com.au

      # ===== SECURITY =====
      # CRITICAL: Generate with: openssl rand -hex 32
      # Or PowerShell: -join ((0..31) | ForEach-Object { '{0:x2}' -f (Get-Random -Minimum 0 -Maximum 255) })
      - SECRET_KEY=a3f5e8d2c1b4a6f9e2d5c8b1a4f7e0d3c6b9a2f5e8d1c4b7a0f3e6d9c2b5a8f1

      # Optional: Password protect your addon (comma-separated for multiple)
      - ADDON_PASSWORD=DavoKazem12!@

      # ===== DATABASE =====
      - DATABASE_URI=postgresql://aiostreams:aiostreams@postgres:5432/aiostreams

      # ===== TIMEZONE =====
      - TZ=Australia/Melbourne
      - LOG_TIMEZONE=Australia/Melbourne

      # ===== BUILT-IN ADDON CONFIGURATION =====
      - BUILTIN_STREMTHRU_URL=https://stremthru.13377001.xyz
      - BUILTIN_SCRAPE_WITH_ALL_TITLES=false
      - BUILTIN_ZILEAN_URL=https://zilean.elfhosted.com
      - BUILTIN_ANIMETOSHO_URL=https://feed.animetosho.org

      # ===== DEBRID SERVICE API KEYS =====
      # Uncomment and add your API keys for the services you use
      # - DEFAULT_REALDEBRID_API_KEY=your_key_here
      # - DEFAULT_ALLDEBRID_API_KEY=your_key_here
      - DEFAULT_PREMIUMIZE_API_KEY=wqnc5canktn82xky
      # - DEFAULT_DEBRIDLINK_API_KEY=your_key_here
      # - DEFAULT_TORBOX_API_KEY=your_key_here

      # ===== TMDB & TRAKT =====
      # Optional: Provide TMDB token for better title matching
      - TMDB_ACCESS_TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlNmE5N2ZlZWY4MGI4MzVhOTdkNTdmMDU1YTFmOTc0MyIsIm5iZiI6MTczNjY0NDUyNy4yNTksInN1YiI6IjY3ODMxN2FmMmIyOWE5MThkMDRlYzIzOCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.o5HIxADy9mSrDViw3f623ZoLAnR6sYNBiymLnFeeqs8
      # - TMDB_API_KEY=your_key_here
      # - TRAKT_CLIENT_ID=your_client_id_here

      # ===== FEATURE CONTROL =====
      - DISABLE_SELF_SCRAPING=false
      - REGEX_FILTER_ACCESS=trusted
      - ENABLE_SEARCH_API=true

      # ===== LOGGING =====
      - LOG_LEVEL=http
      - LOG_FORMAT=text
      - LOG_SENSITIVE_INFO=true

      # ===== RATE LIMITS =====
      - DISABLE_RATE_LIMITS=false

      # ===== CONFIGURATION LIMITS =====
      - MAX_ADDONS=150
      - MAX_GROUPS=20
      - MAX_KEYWORD_FILTERS=300
      - MAX_STREAM_EXPRESSION_FILTERS=300
      - MAX_TIMEOUT=50000
      - MIN_TIMEOUT=1000
      - DEFAULT_TIMEOUT=15000

      # ===== CACHE CONFIGURATION =====
      - DEFAULT_MAX_CACHE_SIZE=100000
      - PROXY_IP_CACHE_TTL=900
      - MANIFEST_CACHE_TTL=21600
      - SUBTITLE_CACHE_TTL=300
      - STREAM_CACHE_TTL=-1
      - CATALOG_CACHE_TTL=300
      - META_CACHE_TTL=300
      - ADDON_CATALOG_CACHE_TTL=300
      - RPDB_API_KEY_VALIDITY_CACHE_TTL=604800

      # ===== STREAM PROXY (MediaFlow/StremThru) =====
      - DEFAULT_PROXY_ID=mediaflow
      - ENCRYPT_MEDIAFLOW_URLS=true
      - ENCRYPT_STREMTHRU_URLS=true
      - FORCE_PROXY_DISABLE_PROXIED_ADDONS=false

      # ===== ANIME DATABASE =====
      - ANIME_DB_LEVEL_OF_DETAIL=required

      # ===== INACTIVE USER PRUNING =====
      - PRUNE_INTERVAL=86400
      - PRUNE_MAX_DAYS=-1

      # ===== EXTERNAL ADDON URLS =====
      - COMET_URL=https://comet.elfhosted.com/
      - MEDIAFUSION_URL=https://mediafusion.elfhosted.com/
      - JACKETTIO_URL=https://jackettio.elfhosted.com/
      - STREMTHRU_STORE_URL=https://stremthru.13377001.xyz/stremio/store/
      - STREMTHRU_TORZ_URL=https://stremthru.13377001.xyz/stremio/torz/
      - TORRENTIO_URL=https://torrentio.strem.fun/
      - ANIME_KITSU_URL=https://anime-kitsu.strem.fun/
      - OPENSUBTITLES_URL=https://opensubtitles-v3.strem.io/
      - TMDB_ADDON_URL=https://tmdb.elfhosted.com
    volumes:
      - /mnt/data/apps/aiostreams:/app/data
    networks:
      - backend-network
    healthcheck:
      test: wget -qO- http://localhost:3000/api/v1/status
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s

networks:
  backend-network:
    external: true
