version: "3.9"

services:
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    container_name: webtop
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Melbourne
      - SUBFOLDER=/
      - TITLE=Webtop
    volumes:
      - /mnt/data/apps/wtop:/config
      - /mnt/HomeData:/mnt/HomeData:rw
    ports:
      - 8082:3000
      - 8083:3001
    shm_size: "1gb"
    networks:
      - backend-network

networks:
  backend-network:
    external: true